"""Add completed recipes tracking

Revision ID: 845eac99ce08
Revises: 759c9b8c2e3e
Create Date: 2025-04-28 22:59:14.981723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845eac99ce08'
down_revision = '759c9b8c2e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_completed_recipes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_completed_recipes')
    # ### end Alembic commands ###
